[package]
name = "solana-bpf-loader-program"
version = "1.9.0"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-loader-program"
edition = "2018"

[build-dependencies]
regex = "1.5.4"

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
log = "0.4.14"
libsecp256k1 = "0.6.0"
openssl = "^0.10.38"
solana-measure = { path = "../../measure", version = "=1.9.0" }
solana-program-runtime = { path = "../../program-runtime", version = "=1.9.0" }
solana-sdk = { path = "../../sdk", version = "=1.9.0" }
solana_rbpf = "=0.2.15"
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
solana-runtime = { path = "../../runtime", version = "=1.9.0" }

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
